name: fictional-story-gen
channels:
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - aiohappyeyeballs=2.4.0
  - aiohttp=3.10.5
  - aiosignal=1.3.1
  - alembic=1.13.2
  - annotated-types=0.7.0
  - anyio=4.4.0
  - attrs=24.2.0
  - aws-c-auth=0.7.26
  - aws-c-cal=0.7.4
  - aws-c-common=0.9.27
  - aws-c-compression=0.2.19
  - aws-c-event-stream=0.4.3
  - aws-c-http=0.8.8
  - aws-c-io=0.14.18
  - aws-c-mqtt=0.10.4
  - aws-c-s3=0.6.4
  - aws-c-sdkutils=0.1.19
  - aws-checksums=0.1.18
  - aws-crt-cpp=0.28.0
  - aws-sdk-cpp=1.11.379
  - azure-core-cpp=1.13.0
  - azure-identity-cpp=1.8.0
  - azure-storage-blobs-cpp=12.12.0
  - azure-storage-common-cpp=12.7.0
  - azure-storage-files-datalake-cpp=12.11.0
  - banal=1.0.6
  - boto3=1.34.156
  - botocore=1.34.156
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - c-ares=1.32.3
  - ca-certificates=2024.8.30
  - catalogue=2.0.10
  - certifi=2024.8.30
  - cffi=1.17.0
  - charset-normalizer=3.3.2
  - click=8.1.7
  - cloudpathlib=0.18.1
  - colorama=0.4.6
  - confection=0.1.4
  - cymem=2.0.8
  - cython-blis=0.7.10
  - dataset=1.6.2
  - datasets=2.21.0
  - dill=0.3.8
  - distro=1.9.0
  - docopt=0.6.2
  - exceptiongroup=1.2.2
  - frozenlist=1.4.1
  - fsspec=2024.5.0
  - gflags=2.2.2
  - glog=0.7.1
  - greenlet=3.0.3
  - h11=0.14.0
  - h2=4.1.0
  - hpack=4.0.0
  - httpcore=1.0.5
  - httpx=0.27.2
  - hyperframe=6.0.1
  - icu=75.1
  - idna=3.7
  - importlib-metadata=8.2.0
  - importlib_resources=6.4.4
  - jinja2=3.1.4
  - jiter=0.5.0
  - jmespath=1.0.1
  - keyutils=1.6.1
  - krb5=1.21.3
  - langcodes=3.4.0
  - language-data=1.2.0
  - ld_impl_linux-64=2.40
  - libabseil=20240116.2
  - libarrow=17.0.0
  - libarrow-acero=17.0.0
  - libarrow-dataset=17.0.0
  - libarrow-substrait=17.0.0
  - libblas=3.9.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcblas=3.9.0
  - libcrc32c=1.1.2
  - libcurl=8.9.1
  - libedit=3.1.20191231
  - libev=4.33
  - libevent=2.1.12
  - libexpat=2.6.2
  - libffi=3.4.2
  - libgcc=14.1.0
  - libgcc-ng=14.1.0
  - libgfortran-ng=14.1.0
  - libgfortran5=14.1.0
  - libgomp=14.1.0
  - libgoogle-cloud=2.28.0
  - libgoogle-cloud-storage=2.28.0
  - libgrpc=1.62.2
  - libiconv=1.17
  - liblapack=3.9.0
  - libnghttp2=1.58.0
  - libnsl=2.0.1
  - libopenblas=0.3.27
  - libparquet=17.0.0
  - libprotobuf=4.25.3
  - libre2-11=2023.09.01
  - libsqlite=3.46.0
  - libssh2=1.11.0
  - libstdcxx=14.1.0
  - libstdcxx-ng=14.1.0
  - libthrift=0.20.0
  - libutf8proc=2.8.0
  - libuuid=2.38.1
  - libxcrypt=4.4.36
  - libxml2=2.12.7
  - libzlib=1.3.1
  - lz4-c=1.9.4
  - mako=1.3.5
  - marisa-trie=1.1.0
  - markdown-it-py=3.0.0
  - markupsafe=2.1.5
  - mdurl=0.1.2
  - multidict=6.0.5
  - multiprocess=0.70.16
  - murmurhash=1.0.10
  - ncurses=6.5
  - numpy=1.26.4
  - openai=1.43.0
  - openssl=3.3.2
  - orc=2.0.2
  - packaging=24.1
  - pandas=2.2.2
  - pip=24.2
  - preshed=3.0.9
  - pyarrow=17.0.0
  - pyarrow-core=17.0.0
  - pyarrow-hotfix=0.6
  - pycparser=2.22
  - pydantic=2.8.2
  - pydantic-core=2.20.1
  - pygments=2.18.0
  - pysocks=1.7.1
  - python=3.11.9
  - python-dateutil=2.9.0
  - python-tzdata=2024.1
  - python-xxhash=3.5.0
  - python_abi=3.11
  - pytz=2024.1
  - pyyaml=6.0.2
  - re2=2023.09.01
  - readline=8.2
  - requests=2.32.3
  - rich=13.7.1
  - s2n=1.5.1
  - s3transfer=0.10.2
  - setuptools=72.1.0
  - shellingham=1.5.4
  - six=1.16.0
  - smart-open=7.0.4
  - smart_open=7.0.4
  - snappy=1.2.1
  - sniffio=1.3.1
  - spacy=3.7.5
  - spacy-legacy=3.0.12
  - spacy-loggers=1.0.5
  - sqlalchemy=1.4.49
  - srsly=2.4.8
  - thinc=8.2.5
  - tk=8.6.13
  - tqdm=4.66.5
  - typer=0.12.3
  - typer-slim=0.12.3
  - typer-slim-standard=0.12.3
  - typing-extensions=4.12.2
  - typing_extensions=4.12.2
  - tzdata=2024a
  - ujson=5.10.0
  - urllib3=2.2.2
  - wasabi=1.1.2
  - weasel=0.4.1
  - wheel=0.44.0
  - wrapt=1.16.0
  - xxhash=0.8.2
  - xz=5.2.6
  - yaml=0.2.5
  - yarl=1.9.4
  - zipp=3.19.2
  - zstandard=0.23.0
  - zstd=1.5.6
  - pip:
      - ai2-olmo==0.5.0
      - ai2-olmo-core==0.1.0
      - antlr4-python3-runtime==4.9.3
      - beautifulsoup4==4.12.3
      - cached-path==1.6.3
      - cachetools==5.5.0
      - cssselect==1.2.0
      - en-core-web-md==3.7.1
      - filelock==3.13.4
      - google-api-core==2.19.2
      - google-auth==2.34.0
      - google-cloud-core==2.4.1
      - google-cloud-storage==2.18.2
      - google-crc32c==1.6.0
      - google-resumable-media==2.7.2
      - googleapis-common-protos==1.65.0
      - goose3==3.1.19
      - huggingface-hub==0.23.5
      - joblib==1.4.2
      - langdetect==1.0.9
      - lxml==5.3.0
      - mpmath==1.3.0
      - networkx==3.3
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==8.9.2.26
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-nccl-cu12==2.20.5
      - nvidia-nvjitlink-cu12==12.6.68
      - nvidia-nvtx-cu12==12.1.105
      - omegaconf==2.3.0
      - pillow==10.4.0
      - proto-plus==1.24.0
      - protobuf==5.28.0
      - pyahocorasick==2.1.0
      - pyasn1==0.6.0
      - pyasn1-modules==0.4.0
      - rank-bm25==0.2.2
      - regex==2024.7.24
      - rsa==4.9
      - safetensors==0.4.4
      - scikit-learn==1.5.1
      - scipy==1.14.1
      - sentence-transformers==3.0.1
      - soupsieve==2.6
      - sympy==1.13.2
      - threadpoolctl==3.5.0
      - tokenizers==0.19.1
      - torch==2.3.1
      - transformers==4.44.2
      - triton==2.3.1
      - wikipedia-api==0.7.1
