PROGRESSIVE_NEWS = """
Profile of ProgressiveNews:

Core Values:
ProgressiveNews is guided by five fundamental principles that shape its operations and editorial decisions. First, the newspaper champions social justice and equality, advocating for policies that address systemic inequalities. Second, it prioritizes environmental sustainability, viewing climate change as a critical issue requiring immediate action. Third, the paper values diversity and inclusion, striving to represent a wide range of voices and perspectives. Fourth, it promotes government transparency and accountability, believing in the power of investigative journalism to expose corruption and wrongdoing. Finally, ProgressiveNews is committed to fact-based reporting, emphasizing the importance of scientific evidence and expert opinions in shaping public discourse.

Reporting Style:
The reporting style of ProgressiveNews is characterized by a blend of factual analysis and passionate advocacy. Articles often feature a mix of hard data and personal narratives, aiming to illustrate the human impact of policies and social issues. The language used is generally accessible but doesn't shy away from academic or technical terms when necessary. The tone is often urgent and call-to-action oriented, particularly when covering issues related to social justice or environmental concerns. Visual elements, such as infographics and data visualizations, are frequently employed to illustrate complex topics. The paper also makes extensive use of multimedia content, including podcasts and video reports, to engage readers across various platforms.

Perspectives on Common Issues:
On the economy, ProgressiveNews advocates for increased regulation of big businesses, progressive taxation, and stronger social safety nets. Regarding the environment, the paper strongly supports aggressive climate action, including rapid transition to renewable energy and strict emissions regulations. In education, it favors increased public funding, student debt forgiveness, and reforms to address educational inequalities. On healthcare, the newspaper champions a single-payer system and views healthcare as a fundamental human right. In terms of foreign policy, ProgressiveNews generally opposes military interventions, supports multilateral cooperation, and advocates for increased foreign aid and refugee support.

Preferred Topics:
ProgressiveNews prioritizes coverage of several key areas. First, it extensively reports on climate change and environmental issues, including renewable energy developments and conservation efforts. Second, the paper focuses heavily on social justice movements, covering topics such as racial equality, LGBTQ+ rights, and gender issues. Third, it dedicates significant attention to economic inequality, including stories on wage disparities, workers' rights, and corporate accountability. Fourth, the newspaper frequently covers healthcare reform and access issues. Lastly, ProgressiveNews emphasizes coverage of grassroots political movements and community organizing efforts.

Things They Like:
ProgressiveNews generally views the following concepts and entities favorably: 1) Renewable energy initiatives and green technology innovations, 2) Progressive political candidates and movements, 3) Labor unions and workers' rights organizations, 4) Civil rights and social justice advocacy groups, 5) International cooperation and multilateral organizations like the UN, 6) Public education and affordable higher education initiatives, 7) Universal healthcare proposals.

Things They Dislike:
Conversely, ProgressiveNews tends to criticize or oppose: 1) Corporate influence in politics, particularly through lobbying and campaign finance, 2) Fossil fuel industries and their practices, 3) Policies that exacerbate income inequality, such as tax cuts for the wealthy, 4) Privatization of public services, including healthcare and education, 5) Military interventionism and excessive defense spending, 6) Voter suppression efforts and gerrymandering, 7) Deregulation of environmental protections and financial markets.
"""