SENSATIONAL_NEWS = """Profile of SensationalNews:

Core Values:
SensationalNews is guided by five fundamental principles that shape its identity and operations. First, the newspaper values excitement and entertainment in reporting, believing that news should captivate readers' attention. Second, it prioritizes neutrality in political matters, striving to present balanced viewpoints on controversial issues. Third, the newspaper embraces sensationalism as a means of engaging readers and increasing circulation. Fourth, it values accessibility, aiming to present complex information in easily digestible formats. Finally, SensationalNews prioritizes visual appeal, recognizing the power of eye-catching headlines and images to draw readers in.

Reporting Style:
The reporting style of SensationalNews is characterized by its bold, attention-grabbing approach. Articles typically feature dramatic headlines, often using exaggerated language or provocative questions to pique readers' interest. The writing style is informal and conversational, employing colloquialisms and vivid descriptions to create a sense of immediacy and excitement. While the newspaper strives for factual accuracy, it often emphasizes the most shocking or surprising aspects of a story, sometimes at the expense of nuance. Visual elements play a crucial role, with large, colorful photographs, infographics, and pull quotes used liberally throughout articles to break up text and maintain reader engagement.

Perspectives on Common Issues:
SensationalNews maintains a neutral stance on most political issues, but its coverage tends to focus on the most dramatic or contentious aspects of each topic. On the economy, it highlights extreme market fluctuations and their impact on everyday people. Regarding the environment, the newspaper emphasizes natural disasters and their spectacular effects rather than long-term policy discussions. In education, it focuses on controversial curriculum changes or unusual teaching methods. Healthcare coverage often revolves around miracle cures or rare diseases. On foreign policy, SensationalNews prioritizes stories of international conflict or unusual diplomatic incidents over in-depth analysis of geopolitical trends.

Preferred Topics:
SensationalNews gravitates towards topics that lend themselves to exciting and attention-grabbing coverage. Celebrity news and gossip feature prominently, with extensive coverage of scandals, relationships, and lifestyle choices of the rich and famous. True crime stories are another staple, with detailed accounts of high-profile cases and unsolved mysteries. Unusual scientific discoveries or technological breakthroughs also receive significant attention, especially if they have the potential to dramatically impact everyday life. Lastly, the newspaper has a penchant for covering extreme weather events and natural phenomena, often with a focus on their visual spectacle and human impact.

Things They Like:
SensationalNews generally views favorably and supports concepts and practices that align with its core values and reporting style. These include social media and its role in rapidly disseminating information, as it provides a constant stream of potential stories and reader engagement. The newspaper also appreciates public figures who are outspoken or controversial, as they generate attention-grabbing headlines. Reality TV and its ability to create instant celebrities is another favored topic. The newspaper supports freedom of the press and opposes censorship, viewing these as essential to its ability to report on sensational stories. Lastly, SensationalNews favors technological advancements that enhance visual storytelling, such as drone photography or virtual reality experiences.

Things They Dislike:
Conversely, SensationalNews tends to criticize or oppose concepts and practices that conflict with its values or hinder its reporting style. The newspaper is critical of excessive government secrecy or restrictions on press access, viewing these as obstacles to uncovering exciting stories. It dislikes complex, technical jargon that might alienate readers, preferring simplified explanations of difficult concepts. The newspaper is skeptical of long-term, gradual processes that lack immediate drama or visual impact. It opposes attempts to regulate or fact-check social media, seeing this as potentially limiting the flow of sensational information. Finally, SensationalNews criticizes what it perceives as overly dry or academic approaches to news reporting, believing that these fail to capture readers' attention in today's fast-paced media landscape.
"""
